### ISSUE TITLE
Sort talks in playlist

### ISSUE THREAD

**Issue by mgax** [esquire900/tmi-archive#11]
The playlist edit page currently says _Talks are not sortable at the moment._ I've created https://tmi-archive.com/playlist/4 and was a bit frustrated to see the talks are not in order, which is kind of important for this playlist to work :)

**Comment by mgax** [comment]
The editor uses [django-select2](https://django-select2.readthedocs.io/en/latest/), and the only reference to sorting that I was able to find was this issue, saying basically "nope, not supported": https://github.com/codingjoe/django-select2/issues/109.

---
Another solution is to implement a custom widget, using [SortableJS](https://sortablejs.github.io/Sortable/). @esquire900 I can take a stab at it if you think it's a good idea.

**Comment by esquire900** [comment]
@mgax I was just tinkering with the idea and stumbled upon the idea below, which seems similar to what you have in mind. Seems easy to implement and I was going to do it today, but if you want to take this one, feel more than welcome :)

https://stackoverflow.com/questions/19522331/saving-model-sort-order-with-django-and-jquery-ajax

**Comment by mgax** [comment]
> Seems easy to implement and I was going to do it today, but if you want to take this one, feel more than welcome :)

Alright, will do, thanks!
