### ISSUE TITLE
Assets not loading on the create-playlist page

### ISSUE THREAD

**Issue by mgax** [esquire900/tmi-archive#7]
On https://tmi-archive.com/playlist/create it's not possible to select talks for the playlist, possibly because assets are not loading:

<img width="1169" alt="Screenshot 2022-02-18 at 13 25 23" src="https://user-images.githubusercontent.com/27617/154674035-a5e5e499-3a21-4cd1-8394-130487f049ec.png">

**Comment by esquire900** [comment]
After a though struggle with static files this is finally fixed, thanks for notifying me :)

**Comment by mgax** [comment]
> After a though struggle with static files this is finally fixed, thanks for notifying me :)

I can confirm the assets load fine. Thanks for solving this!
